export const dynamic = "force-dynamic";

export default function PlaybooksPage() {
  return (
    <div style={{ maxWidth: 1000, margin: "0 auto" }}>
      <div style={{ marginBottom: 40 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: 8,
          }}
        >
          <span style={{ fontSize: 24 }}>📖</span>
          <h1
            style={{
              fontSize: 28,
              fontWeight: 700,
              color: "#fafafa",
              margin: 0,
              letterSpacing: "-0.02em",
            }}
          >
            Playbooks
          </h1>
        </div>
        <p style={{ fontSize: 14, color: "#71717a", margin: 0 }}>
          Institutional playbooks and operational guides
        </p>
      </div>

      <div
        style={{
          padding: 60,
          textAlign: "center",
          background: "#18181b",
          border: "1px solid #27272a",
          borderRadius: 12,
        }}
      >
        <div style={{ fontSize: 48, marginBottom: 16 }}>📖</div>
        <div
          style={{
            fontSize: 16,
            fontWeight: 600,
            color: "#fafafa",
            marginBottom: 8,
          }}
        >
          Playbooks are generated by the institutional-playbooks module
        </div>
        <p
          style={{
            fontSize: 14,
            color: "#71717a",
            marginBottom: 24,
            maxWidth: 440,
            margin: "0 auto 24px",
          }}
        >
          Operational playbooks are dynamically generated from governance docs,
          policies, and institutional knowledge. They are not stored as static
          files.
        </p>
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            padding: "10px 20px",
            background: "#1c1c1f",
            border: "1px solid #27272a",
            borderRadius: 8,
            fontSize: 13,
            color: "#a1a1aa",
          }}
        >
          <span style={{ fontFamily: "monospace" }}>
            institutional-playbooks
          </span>
          <span style={{ color: "#52525b" }}>·</span>
          <span>Runtime module</span>
        </div>
      </div>
    </div>
  );
}
