import type { Experiment, Reflection, PortfolioArtifact } from "../types";

let counter = 0;

export class PortfolioGenerator {
  generate(params: {
    lessonId: string;
    title: string;
    description: string;
    skills: string[];
    knowledgePackages?: string[];
    repositories?: string[];
    technologies?: string[];
    experiments: Experiment[];
    reflections: Reflection[];
  }): PortfolioArtifact {
    const { experiments, reflections } = params;
    const best =
      experiments.length > 0
        ? experiments.reduce((b, e) => (e.prompt.length > b.prompt.length ? e : b))
        : experiments[0];

    const scores = experiments.map((e) => {
      const words = e.prompt.split(/\s+/).length;
      let s = 0;
      if (words >= 5) s += 20;
      if (/[.:;,]/.test(e.prompt)) s += 20;
      if (e.prompt.length > 60) s += 20;
      if (/explain to|for a/i.test(e.prompt)) s += 20;
      if (/step by step|json|list/i.test(e.prompt)) s += 10;
      if (/example|for instance/i.test(e.prompt)) s += 10;
      return Math.min(s, 100);
    });

    const first = scores[0] || 0;
    const bestScore = Math.max(...scores, 0);
    const improvement = first > 0 ? Math.round(((bestScore - first) / first) * 100) : bestScore > 0 ? 100 : 0;

    return {
      id: "artifact-" + Date.now() + "-" + ++counter,
      lessonId: params.lessonId,
      title: params.title,
      description: params.description,
      skills: params.skills,
      knowledgePackages: params.knowledgePackages || [],
      repositories: params.repositories || [],
      technologies: params.technologies || [],
      experiments,
      reflections,
      bestAttempt: best || experiments[0],
      improvementRate: improvement,
      totalAttempts: experiments.length,
      reflectionDepth: 0,
      createdAt: Date.now(),
    };
  }

  exportJSON(artifact: PortfolioArtifact): string {
    return JSON.stringify(artifact, null, 2);
  }

  exportHTML(artifact: PortfolioArtifact): string {
    const expRows = artifact.experiments
      .map(
        (e, i) =>
          `<tr><td>${i + 1}</td><td>${esc(e.prompt)}</td><td>${esc(e.output.slice(0, 100))}...</td></tr>`
      )
      .join("\n");

    return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${esc(artifact.title)}</title>
<style>body{font-family:system-ui;max-width:800px;margin:2rem auto;padding:0 1rem;color:#e2e8f0;background:#0f172a}
h1{color:#60a5fa}table{width:100%;border-collapse:collapse}td,th{border:1px solid #334155;padding:8px;text-align:left}
th{background:#1e293b}</style></head>
<body>
<h1>${esc(artifact.title)}</h1>
<p>${esc(artifact.description)}</p>
<h2>Skills</h2><ul>${artifact.skills.map((s) => `<li>${esc(s)}</li>`).join("")}</ul>
<h2>Experiments</h2><table><tr><th>#</th><th>Prompt</th><th>Output</th></tr>${expRows}</table>
<h2>Improvement</h2><p>${artifact.improvementRate}% improvement over ${artifact.totalAttempts} attempts</p>
<p><em>Generated by Bhavya AI Institute</em></p>
</body></html>`;
  }
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
