import { KnowledgeEntry } from "./types.js";

export const knowledgeBase: KnowledgeEntry[] = [
  {
    id: "ai-001",
    topic: "AI Basics",
    subtopic: "What is AI",
    difficulty: "beginner",
    patterns: [
      "what is ai",
      "what is artificial intelligence",
      "define ai",
      "explain ai",
      "what does ai mean",
      "introduction to ai",
    ],
    answer:
      "Artificial Intelligence (AI) is the simulation of human intelligence by machines. It encompasses systems that can learn from data, recognize patterns, make decisions, and solve problems. Think of it like teaching a computer to think — not like a human, but in a way that's useful for specific tasks. Just as you learn from experience, AI learns from data.",
    followUpQuestions: [
      "How does AI learn from data?",
      "What are the different types of AI?",
      "How is AI used in everyday life?",
    ],
    relatedConcepts: [
      "machine learning",
      "neural networks",
      "deep learning",
      "data science",
    ],
  },
  {
    id: "ai-002",
    topic: "AI Basics",
    subtopic: "Types of AI",
    difficulty: "beginner",
    patterns: [
      "types of ai",
      "kinds of ai",
      "different ai",
      "narrow ai vs general ai",
      "artificial general intelligence",
      "agi",
    ],
    answer:
      "There are three main types of AI: 1) Narrow AI — systems designed for one specific task (like Siri or a chess program), 2) General AI (AGI) — machines that can perform any intellectual task a human can (not yet achieved), 3) Super AI — hypothetical AI that surpasses human intelligence. Most AI today is narrow AI. Imagine it like this: a calculator is narrow AI at arithmetic, while a human can do math, paint, cook, and have conversations.",
    followUpQuestions: [
      "What is an example of narrow AI?",
      "When might we achieve AGI?",
      "What is machine learning?",
    ],
    relatedConcepts: [
      "machine learning",
      "artificial general intelligence",
      "deep learning",
      "narrow ai",
    ],
  },
  {
    id: "ml-001",
    topic: "Machine Learning",
    subtopic: "What is ML",
    difficulty: "beginner",
    patterns: [
      "what is machine learning",
      "define machine learning",
      "explain machine learning",
      "how does ml work",
      "introduction to machine learning",
    ],
    answer:
      "Machine Learning is a subset of AI where systems learn patterns from data instead of being explicitly programmed. Think of it like teaching a child to recognize animals — instead of listing every feature, you show many examples and they learn to identify patterns themselves. The three main types are: Supervised Learning (learning from labeled examples), Unsupervised Learning (finding patterns in unlabeled data), and Reinforcement Learning (learning through trial and reward).",
    followUpQuestions: [
      "What is supervised vs unsupervised learning?",
      "How does a neural network learn?",
      "What is a training dataset?",
    ],
    relatedConcepts: [
      "deep learning",
      "neural networks",
      "supervised learning",
      "unsupervised learning",
      "reinforcement learning",
    ],
  },
  {
    id: "ml-002",
    topic: "Machine Learning",
    subtopic: "Supervised Learning",
    difficulty: "intermediate",
    patterns: [
      "supervised learning",
      "labeled data",
      "classification",
      "regression",
      "how does supervised learning work",
    ],
    answer:
      "Supervised Learning is like learning with a teacher who provides the correct answers. You feed the algorithm labeled data — input-output pairs — and it learns the mapping. There are two main types: Classification (predicting categories, like spam vs not spam) and Regression (predicting continuous values, like house prices). The algorithm tries to find a function that maps inputs to outputs accurately.",
    followUpQuestions: [
      "What is the difference between classification and regression?",
      "How do you evaluate a supervised learning model?",
      "What is overfitting?",
    ],
    relatedConcepts: [
      "classification",
      "regression",
      "training data",
      "overfitting",
      "test set",
    ],
  },
  {
    id: "ml-003",
    topic: "Machine Learning",
    subtopic: "Unsupervised Learning",
    difficulty: "intermediate",
    patterns: [
      "unsupervised learning",
      "clustering",
      "k-means",
      "dimensionality reduction",
      "pca",
    ],
    answer:
      "Unsupervised Learning works with unlabeled data — the algorithm must find structure on its own. Think of it like sorting a pile of unlabeled buttons by shape and color without being told the categories. Common techniques include Clustering (grouping similar items, like K-Means) and Dimensionality Reduction (simplifying data while keeping important information, like PCA).",
    followUpQuestions: [
      "What is K-Means clustering?",
      "When would you use PCA?",
      "What is the difference between clustering and classification?",
    ],
    relatedConcepts: [
      "clustering",
      "k-means",
      "pca",
      "dimensionality reduction",
      "anomaly detection",
    ],
  },
  {
    id: "dl-001",
    topic: "Deep Learning",
    subtopic: "What is Deep Learning",
    difficulty: "intermediate",
    patterns: [
      "what is deep learning",
      "explain deep learning",
      "deep learning vs machine learning",
      "neural networks",
      "artificial neural networks",
    ],
    answer:
      "Deep Learning is a subset of machine learning using neural networks with many layers (hence 'deep'). While traditional ML uses hand-crafted features, deep learning automatically learns features from raw data. Think of it like this: traditional ML is like a chef who follows a recipe, while deep learning is like learning to cook by tasting thousands of dishes. Deep learning excels at image recognition, natural language processing, and complex pattern recognition.",
    followUpQuestions: [
      "How do neural networks learn?",
      "What is a convolutional neural network?",
      "What is the difference between deep learning and traditional ML?",
    ],
    relatedConcepts: [
      "convolutional neural networks",
      "recurrent neural networks",
      "transformers",
      "backpropagation",
    ],
  },
  {
    id: "dl-002",
    topic: "Deep Learning",
    subtopic: "CNNs",
    difficulty: "intermediate",
    patterns: [
      "cnn",
      "convolutional neural network",
      "convolution",
      "image recognition",
      "how do cnns work",
    ],
    answer:
      "Convolutional Neural Networks (CNNs) are designed for visual data. They use convolutional layers that apply filters to detect features like edges, textures, and shapes. Think of it like looking at a photo through different colored glasses — each glass highlights something different. CNNs stack these layers so early layers detect simple features (edges) and deeper layers detect complex ones (faces, objects).",
    followUpQuestions: [
      "What is a convolution operation?",
      "How are CNNs used in image classification?",
      "What is pooling in CNNs?",
    ],
    relatedConcepts: [
      "convolution",
      "pooling",
      "feature maps",
      "resnet",
      "image classification",
    ],
  },
  {
    id: "dl-003",
    topic: "Deep Learning",
    subtopic: "RNNs",
    difficulty: "intermediate",
    patterns: [
      "rnn",
      "recurrent neural network",
      "sequence modeling",
      "lstm",
      "gru",
      "time series",
    ],
    answer:
      "Recurrent Neural Networks (RNNs) are designed for sequential data like text or time series. Unlike feedforward networks, RNNs have loops that allow information to persist. Think of reading a sentence — you need to remember previous words to understand the current one. LSTM and GRU are improved versions that handle long-range dependencies better by learning what to remember and what to forget.",
    followUpQuestions: [
      "What is the vanishing gradient problem?",
      "How does LSTM work?",
      "When should I use RNNs vs Transformers?",
    ],
    relatedConcepts: [
      "lstm",
      "gru",
      "sequence modeling",
      "vanishing gradient",
      "transformers",
    ],
  },
  {
    id: "transformer-001",
    topic: "Transformers",
    subtopic: "What are Transformers",
    difficulty: "advanced",
    patterns: [
      "what is a transformer",
      "transformer architecture",
      "attention mechanism",
      "self-attention",
      "how do transformers work",
    ],
    answer:
      "Transformers are a neural network architecture that revolutionized NLP through self-attention. Instead of processing data sequentially like RNNs, transformers process all positions simultaneously. The self-attention mechanism lets each word consider all other words when building its representation — like reading a sentence and understanding each word in context of every other word. This enables massive parallelization and captures long-range dependencies far better than RNNs.",
    followUpQuestions: [
      "How does self-attention work?",
      "What is multi-head attention?",
      "What is positional encoding?",
    ],
    relatedConcepts: [
      "self-attention",
      "multi-head attention",
      "positional encoding",
      "bert",
      "gpt",
    ],
  },
  {
    id: "transformer-002",
    topic: "Transformers",
    subtopic: "Attention Mechanism",
    difficulty: "advanced",
    patterns: [
      "explain attention",
      "self attention",
      "multi head attention",
      "qkv",
      "query key value",
      "scaled dot product attention",
    ],
    answer:
      "Attention is a mechanism that lets a model focus on relevant parts of the input. Self-attention computes Query, Key, and Value matrices for each token. Think of it like searching a library — Query is what you're looking for, Key is the index label on each book, and Value is the book's content. You compute similarity between Query and all Keys to decide how much attention to pay to each Value. Multi-head attention runs this in parallel with different learned projections.",
    followUpQuestions: [
      "What is the difference between dot-product and additive attention?",
      "Why do we need multi-head attention?",
      "How is attention used in vision transformers?",
    ],
    relatedConcepts: [
      "self-attention",
      "multi-head attention",
      "positional encoding",
      "vision transformer",
    ],
  },
  {
    id: "llm-001",
    topic: "LLMs",
    subtopic: "What are LLMs",
    difficulty: "intermediate",
    patterns: [
      "what is an llm",
      "large language model",
      "how do llms work",
      "gpt",
      "chatgpt",
      "how was gpt trained",
    ],
    answer:
      "Large Language Models (LLMs) are transformer-based neural networks trained on massive text datasets. They learn to predict the next token in a sequence, developing emergent abilities like reasoning, coding, and translation. Training involves pre-training (learning language patterns from vast text), fine-tuning (specializing for tasks), and alignment (making outputs helpful and safe). Models like GPT-4, Claude, and LLaMA are all LLMs.",
    followUpQuestions: [
      "What is tokenization?",
      "How does RLHF work?",
      "What are the limitations of LLMs?",
    ],
    relatedConcepts: [
      "transformers",
      "tokenization",
      "rlhf",
      "pre-training",
      "fine-tuning",
    ],
  },
  {
    id: "llm-002",
    topic: "LLMs",
    subtopic: "Training LLMs",
    difficulty: "advanced",
    patterns: [
      "how to train an llm",
      "pre-training",
      "fine-tuning",
      "rlhf",
      "instruct gpt",
      "alignment",
    ],
    answer:
      "LLM training has three phases: 1) Pre-training — the model learns language patterns from trillions of tokens using next-token prediction, 2) Supervised Fine-Tuning (SFT) — training on curated instruction-response pairs, 3) RLHF — using human preferences to align outputs with human values. Think of it like education: pre-training is reading millions of books, SFT is practicing with a tutor, and RLHF is getting feedback from mentors.",
    followUpQuestions: [
      "What is instruction tuning?",
      "How does RLHF use reward models?",
      "What is constitutional AI?",
    ],
    relatedConcepts: [
      "pre-training",
      "supervised fine-tuning",
      "rlhf",
      "reward model",
      "constitutional ai",
    ],
  },
  {
    id: "python-001",
    topic: "Python",
    subtopic: "Python Basics",
    difficulty: "beginner",
    patterns: [
      "python basics",
      "learn python",
      "python programming",
      "variables in python",
      "data types python",
      "introduction to python",
    ],
    answer:
      "Python is a high-level, interpreted programming language known for its readability and simplicity. Key concepts: Variables store data (no declaration needed), Data Types include int, float, str, bool, list, dict, Control Flow uses if/elif/else and for/while loops, Functions are defined with 'def'. Python reads almost like English — that's why it's great for beginners and AI development.",
    followUpQuestions: [
      "How do lists work in Python?",
      "What are dictionaries in Python?",
      "How do I write functions in Python?",
    ],
    relatedConcepts: [
      "lists",
      "dictionaries",
      "functions",
      "loops",
      "data types",
    ],
  },
  {
    id: "python-002",
    topic: "Python",
    subtopic: "NumPy",
    difficulty: "intermediate",
    patterns: [
      "numpy",
      "what is numpy",
      "numpy arrays",
      "matrix operations",
      "numpy tutorial",
    ],
    answer:
      "NumPy is Python's numerical computing library, providing fast array operations. Think of it as Excel on steroids — but for scientific computing. Key features: ndarray (N-dimensional arrays), broadcasting (operations on different-shaped arrays), vectorization (no loops needed), and integration with C for speed. Most ML libraries (TensorFlow, PyTorch) use NumPy arrays under the hood.",
    followUpQuestions: [
      "What is broadcasting?",
      "How do I reshape arrays?",
      "What is the difference between a list and a NumPy array?",
    ],
    relatedConcepts: [
      "arrays",
      "broadcasting",
      "vectorization",
      "linear algebra",
      "matrix operations",
    ],
  },
  {
    id: "python-003",
    topic: "Python",
    subtopic: "Pandas",
    difficulty: "intermediate",
    patterns: [
      "pandas",
      "what is pandas",
      "dataframes",
      "data manipulation",
      "pandas tutorial",
    ],
    answer:
      "Pandas is Python's data manipulation library. Its two main structures are Series (1D labeled array) and DataFrame (2D table, like a spreadsheet). Key operations: read_csv, groupby, merge, pivot, apply. Think of it as SQL meets Excel in Python. For ML, you use Pandas to clean, transform, and prepare data before training models.",
    followUpQuestions: [
      "How do I read CSV files with Pandas?",
      "What is groupby?",
      "How do I handle missing data?",
    ],
    relatedConcepts: [
      "dataframes",
      "series",
      "data cleaning",
      "data transformation",
      "eda",
    ],
  },
  {
    id: "math-001",
    topic: "Math",
    subtopic: "Linear Algebra",
    difficulty: "intermediate",
    patterns: [
      "linear algebra",
      "matrices",
      "vectors",
      "matrix multiplication",
      "dot product",
      "eigenvalues",
    ],
    answer:
      "Linear algebra is the backbone of ML. Key concepts: Vectors (data points, like [3, 4]), Matrices (data tables and transformations), Dot Product (measure of similarity between vectors), Matrix Multiplication (combining transformations). In neural networks, every layer is a matrix multiplication followed by an activation function. Think of matrices as machines that transform data — rotating, scaling, or projecting it.",
    followUpQuestions: [
      "What is a dot product?",
      "How does matrix multiplication work?",
      "What are eigenvalues used for?",
    ],
    relatedConcepts: [
      "vectors",
      "matrices",
      "dot product",
      "matrix multiplication",
      "linear transformation",
    ],
  },
  {
    id: "math-002",
    topic: "Math",
    subtopic: "Calculus",
    difficulty: "intermediate",
    patterns: [
      "calculus",
      "derivatives",
      "gradient",
      "gradient descent",
      "backpropagation",
      "chain rule",
    ],
    answer:
      "Calculus powers how neural networks learn. Key concepts: Derivatives (rate of change — how much output changes with input), Gradient (vector of all partial derivatives — direction of steepest increase), Gradient Descent (moving in the direction that reduces error). In backpropagation, we compute gradients layer by layer using the chain rule, then adjust weights to minimize loss. Think of it like rolling a ball downhill to find the lowest point.",
    followUpQuestions: [
      "What is the chain rule?",
      "How does gradient descent work?",
      "What is backpropagation?",
    ],
    relatedConcepts: [
      "gradient descent",
      "backpropagation",
      "loss function",
      "optimization",
      "chain rule",
    ],
  },
  {
    id: "math-003",
    topic: "Math",
    subtopic: "Probability",
    difficulty: "intermediate",
    patterns: [
      "probability",
      "statistics",
      "bayes theorem",
      "conditional probability",
      "probability distribution",
      "normal distribution",
    ],
    answer:
      "Probability quantifies uncertainty. Key concepts: Probability (0-1 likelihood), Conditional Probability (likelihood given evidence), Bayes Theorem (updating beliefs with new evidence). In ML, models output probability distributions — e.g., 'this image is 90% cat, 10% dog'. Bayesian thinking is fundamental to understanding how models make decisions under uncertainty.",
    followUpQuestions: [
      "What is Bayes theorem?",
      "How do neural networks output probabilities?",
      "What is a probability distribution?",
    ],
    relatedConcepts: [
      "bayes theorem",
      "probability distribution",
      "softmax",
      "cross-entropy",
      "bayesian inference",
    ],
  },
  {
    id: "nlp-001",
    topic: "NLP",
    subtopic: "What is NLP",
    difficulty: "beginner",
    patterns: [
      "what is nlp",
      "natural language processing",
      "nlp basics",
      "text processing",
      "how do computers understand text",
    ],
    answer:
      "Natural Language Processing (NLP) enables computers to understand, interpret, and generate human language. Tasks include: sentiment analysis (detecting emotion), machine translation, text summarization, question answering, and chatbots. The challenge is that language is ambiguous — 'bank' can mean a financial institution or a riverbank. Modern NLP uses transformers to capture context and nuance.",
    followUpQuestions: [
      "How does sentiment analysis work?",
      "What is tokenization?",
      "How do chatbots work?",
    ],
    relatedConcepts: [
      "tokenization",
      "sentiment analysis",
      "transformers",
      "bert",
      "gpt",
    ],
  },
  {
    id: "nlp-002",
    topic: "NLP",
    subtopic: "Tokenization",
    difficulty: "intermediate",
    patterns: [
      "tokenization",
      "what is tokenization",
      "subword",
      "bpe",
      "byte pair encoding",
      "tokenizer",
    ],
    answer:
      "Tokenization splits text into tokens (subwords or words) for model processing. There are word-level (split on spaces), character-level (each letter), and subword-level (BPE, WordPiece, SentencePiece) tokenizers. Subword tokenization is most common — it handles rare words by breaking them into known subwords. For example, 'unhappiness' might become ['un', 'happi', 'ness']. This balances vocabulary size with coverage.",
    followUpQuestions: [
      "What is BPE?",
      "Why do we need special tokens?",
      "How do tokenizers handle different languages?",
    ],
    relatedConcepts: [
      "bpe",
      "wordpiece",
      "sentencepiece",
      "vocabulary",
      "special tokens",
    ],
  },
  {
    id: "cv-001",
    topic: "Computer Vision",
    subtopic: "What is CV",
    difficulty: "beginner",
    patterns: [
      "what is computer vision",
      "cv basics",
      "image recognition",
      "object detection",
      "how do computers see",
    ],
    answer:
      "Computer Vision (CV) enables computers to interpret visual information from images and videos. Tasks include: Image Classification (what is this?), Object Detection (where are objects?), Segmentation (pixel-level labeling), and Generation (creating images). Modern CV uses CNNs and Vision Transformers. Think of it like teaching a computer to see and understand what it sees, similar to how our eyes and brain process visual information.",
    followUpQuestions: [
      "How does image classification work?",
      "What is the difference between detection and segmentation?",
      "How are Vision Transformers different from CNNs?",
    ],
    relatedConcepts: [
      "cnn",
      "vision transformer",
      "image classification",
      "object detection",
      "segmentation",
    ],
  },
  {
    id: "rl-001",
    topic: "Reinforcement Learning",
    subtopic: "What is RL",
    difficulty: "advanced",
    patterns: [
      "what is reinforcement learning",
      "rl basics",
      "rewards",
      "policy",
      "q learning",
      "exploration vs exploitation",
    ],
    answer:
      "Reinforcement Learning (RL) trains agents to make decisions by maximizing cumulative reward. An agent takes actions in an environment, receives rewards/penalties, and learns a policy (strategy). Think of training a dog: you give treats for good behavior and nothing for bad, and the dog learns which actions lead to rewards. Key concepts: Agent, Environment, State, Action, Reward, Policy. The challenge is balancing exploration (trying new things) vs exploitation (using known good actions).",
    followUpQuestions: [
      "What is the exploration-exploitation tradeoff?",
      "How does Q-learning work?",
      "What is a policy gradient?",
    ],
    relatedConcepts: [
      "q learning",
      "policy gradient",
      "reward function",
      "exploration exploitation",
      "deep reinforcement learning",
    ],
  },
];
